export const HOLIDAY_PROMO_PRESETS = [
  {
    value: "black_friday_sale",
    label: "Black Friday Sale",
    holidayValue: "black_friday",
    campaignStyle: "sale_announcement",
    toneIntensity: "more_jagoff",
    platform: "facebook",
    notes: "Black Friday sale push for Facebook and Instagram. Make it punchy, urgent, and not corporate.",
    promoCodeDetails: "",
  },
  {
    value: "cyber_monday_push",
    label: "Cyber Monday Push",
    holidayValue: "cyber_monday",
    campaignStyle: "sale_announcement",
    toneIntensity: "balanced",
    platform: "instagram",
    notes: "Online-only Cyber Monday energy for Facebook and Instagram. Keep it quick and clickable.",
    promoCodeDetails: "",
  },
  {
    value: "small_business_saturday",
    label: "Small Business Saturday",
    holidayValue: "small_business_saturday",
    campaignStyle: "sale_announcement",
    toneIntensity: "balanced",
    platform: "facebook",
    notes: "Shop small, shop local, Western PA attitude. Do not sound like a corporate awareness post.",
    promoCodeDetails: "",
  },
  {
    value: "christmas_gift_push",
    label: "Christmas Gift Push",
    holidayValue: "christmas_holiday",
    campaignStyle: "gift_guide",
    toneIntensity: "balanced",
    platform: "instagram",
    notes: "Gift angle for the local jagoff on your list. Make it funny but useful.",
    promoCodeDetails: "",
  },
  {
    value: "last_chance_holiday",
    label: "Last Chance Holiday",
    holidayValue: "christmas_holiday",
    campaignStyle: "last_chance",
    toneIntensity: "savage_but_safe",
    platform: "facebook",
    notes: "Last chance holiday push. Urgent but do not claim shipping deadlines unless entered in promo details.",
    promoCodeDetails: "",
  },
  {
    value: "thanksgiving_weekend",
    label: "Thanksgiving Weekend",
    holidayValue: "thanksgiving",
    campaignStyle: "weekend_push",
    toneIntensity: "more_jagoff",
    platform: "facebook",
    notes: "Thanksgiving weekend, dinner table jokes, football, local attitude. Keep it post-safe.",
    promoCodeDetails: "",
  },
  {
    value: "mothers_day_gift",
    label: "Mother’s Day Gift",
    holidayValue: "mothers_day",
    campaignStyle: "gift_guide",
    toneIntensity: "balanced",
    platform: "instagram",
    notes: "Gift idea for moms. Funny but not mean. Keep it warm and local.",
    promoCodeDetails: "",
  },
  {
    value: "fathers_day_gift",
    label: "Father’s Day Gift",
    holidayValue: "fathers_day",
    campaignStyle: "gift_guide",
    toneIntensity: "more_jagoff",
    platform: "facebook",
    notes: "Gift idea for dads. Sarcastic, local, and useful.",
    promoCodeDetails: "",
  },
  {
    value: "fourth_cookout",
    label: "Fourth of July Cookout",
    holidayValue: "fourth_of_july",
    campaignStyle: "weekend_push",
    toneIntensity: "balanced",
    platform: "instagram",
    notes: "Cookout, porch, fireworks, summer local attitude. No political angle.",
    promoCodeDetails: "",
  },
  {
    value: "halloween_spooky",
    label: "Halloween / Spooky Season",
    holidayValue: "halloween",
    campaignStyle: "sale_announcement",
    toneIntensity: "savage_but_safe",
    platform: "instagram",
    notes: "Spooky season, funny local jagoff energy. Make it weird but still clean enough to post.",
    promoCodeDetails: "",
  },
];

export function findHolidayPromoPreset(value) {
  return HOLIDAY_PROMO_PRESETS.find((preset) => preset.value === value) || null;
}
