const productImages = {
  428982889: [
    "/images/products/localjagoffkeystonetee.jpg",
    "/images/products/localjagoffkeystonetee-1.jpg",
    "/images/products/localjagoffkeystonetee-2.jpg",
    // "/images/products/localjagoffkeystonetee-4.jpg",
    // "/images/products/localjagoffkeystonetee-5.jpg",
  ],
  429536493: [
  "/images/products/tee-412.jpg",
  "/images/products/tee-412-1.jpg",
  "/images/products/tee-412-2.jpg",
  "/images/products/tee-412-3.jpg",
  "/images/products/tee-412-4.jpg",
],
   429728777: [
  "/images/products/ljstamptee1.jpg",
  "/images/products/ljstamptee2.jpg",
  "/images/products/ljstamptee3.jpg",
  "/images/products/ljstamptee4.jpg",
],
  428980566: [
    "/images/products/localjagoffhatvr2.jpg",
    // "/images/products/localjagoffhatvr2-2.jpg",
    // "/images/products/localjagoffhatvr2-3.jpg",
    // "/images/products/localjagoffhatvr2-4.jpg",
    // "/images/products/localjagoffhatvr2-5.jpg",
  ],
  428851907: [
    "/images/products/localjagoffhat.jpg",
    // "/images/products/localjagoffhat-2.jpg",
    // "/images/products/localjagoffhat-3.jpg",
    // "/images/products/localjagoffhat-4.jpg",
    // "/images/products/localjagoffhat-5.jpg",
  ],
  428851698: [
    "/images/products/tee-keystone.jpg",
    "/images/products/localjagoff-keystoneverse-tee1.jpg",
    "/images/products/localjagoff-keystoneverse-tee2.jpg",
    "/images/products/localjagoff-keystoneverse-tee3.jpg",
    // "/images/products/tee-keystone-5.jpg",
  ],
  428851608: [
    "/images/products/tee-steel.jpg",
    // "/images/products/tee-steel-2.jpg",
    // "/images/products/tee-steel-3.jpg",
    // "/images/products/tee-steel-4.jpg",
    // "/images/products/tee-steel-5.jpg",
  ],
  428851513: [
    "/images/products/local-jagoff-sideways-tee.png",
    // "/images/products/local-jagoff-sideways-tee-2.png",
    // "/images/products/local-jagoff-sideways-tee-3.png",
    // "/images/products/local-jagoff-sideways-tee-4.png",
    // "/images/products/local-jagoff-sideways-tee-5.png",
  ],
  428821578: [
    "/images/products/hoodie2.jpg",
    // "/images/products/hoodie2-2.jpg",
    // "/images/products/hoodie2-3.jpg",
    // "/images/products/hoodie2-4.jpg",
    // "/images/products/hoodie2-5.jpg",
  ],
  428550417: [
    "/images/products/tee-certified.jpg",
    "/images/products/tee-certified-1.jpg",
    "/images/products/tee-certified-2.jpg",
    // "/images/products/tee-certified-4.jpg",
    // "/images/products/tee-certified-5.jpg",
  ],
  428983169: [
    "/images/products/local-jagoff-412-hoodie.jpg",
    // "/images/products/local-jagoff-412-hoodie-2.jpg",
    // "/images/products/local-jagoff-412-hoodie-3.jpg",
    // "/images/products/local-jagoff-412-hoodie-4.jpg",
    // "/images/products/local-jagoff-412-hoodie-5.jpg",
  ],
  429208592: [
    "/images/products/localjagoff-keystone-hoodie01.jpg",
    // "/images/products/localjagoff-keystone-hoodie02.jpg",
    // "/images/products/localjagoff-keystone-hoodie03.jpg",
    // "/images/products/localjagoff-keystone-hoodie04.jpg",
    // "/images/products/localjagoff-keystone-hoodie05.jpg",
  ],
};

export default productImages;
