const fs=require('node:fs');
const path=require('node:path');

const VERSIONS=Object.freeze({'@opennextjs/cloudflare':'1.20.6','@opennextjs/aws':'4.1.4',next:'15.5.25'});
const MARKER='// Local Jagoff prewarm v1: initialize the server before requests.';
const SERVER_IMPORT='const { handler } = await import("./server-functions/default/handler.mjs");';
const REQUEST_IMPORT='            // @ts-expect-error: resolved by wrangler build\n            '+SERVER_IMPORT+'\n';
const ROUTE_CONFIG='open_next_config_default=defineCloudflareConfig2({})';
const WARM_ROUTE_CONFIG='open_next_config_default=defineCloudflareConfig2({routePreloadingBehavior:"onStart"})';
const PAGE_PRELOAD='isAppPath:!1,isDev:this.isDev,sriEnabled:this.sriEnabled}).catch(()=>{});for(let page';
const STRICT_PAGE_PRELOAD='isAppPath:!1,isDev:this.isDev,sriEnabled:this.sriEnabled}).catch(error=>{throw new Error(`OpenNext route prewarm failed: ${page}`,{cause:error})});for(let page';
const APP_PRELOAD='await webpackRequire(id)}).catch(()=>{})}async handleUpgrade()';
const STRICT_APP_PRELOAD='await webpackRequire(id)}).catch(error=>{throw new Error(`OpenNext app prewarm failed: ${page}`,{cause:error})})}async handleUpgrade()';
const ENTRY=`// Generated by scripts/cloudflare-prewarm.cjs; do not edit.
import budget from '../lib/invocation-budget.cjs';
globalThis.fetch=budget.installBudget(globalThis.fetch);
// Await the wrapper before Next: native guards remain owned by the wrapper.
const {default:worker}=await import('../cloudflare-worker.js');
// Middleware and server capture only the budgeted fetch; no synthetic request or env.
await import('./worker.js');
export default worker;
export {CommerceExecutor} from '../cloudflare-commerce-object.js';
`;

function count(source,text){return source.split(text).length-1;}
function patchRoutes(source){
  // Next otherwise swallows preload failures, potentially caching partially initialized routes.
  const replacements=[[ROUTE_CONFIG,WARM_ROUTE_CONFIG],[PAGE_PRELOAD,STRICT_PAGE_PRELOAD],[APP_PRELOAD,STRICT_APP_PRELOAD]];
  const fresh=replacements.every(([before,after])=>count(source,before)===1&&count(source,after)===0);
  const patched=replacements.every(([before,after])=>count(source,before)===0&&count(source,after)===1);
  if(patched)return source;
  if(!fresh)throw new Error('OpenNext route preloader changed or is partially patched; audit startup again');
  for(const [before,after] of replacements)source=source.replace(before,after);
  return source;
}
function patchWorker(source){
  const newline=source.includes('\r\n')?'\r\n':'\n';
  const normalized=source.replaceAll('\r\n','\n');
  const prewarm=MARKER+'\n'+SERVER_IMPORT+'\nexport default {';
  if(count(normalized,'export default {')!==1||count(normalized,SERVER_IMPORT)!==1||
    count(normalized,'return handler(reqOrResp, env, ctx, request.signal);')!==1||
    !normalized.includes('return runWithCloudflareRequestContext(request, env, ctx, async () => {')){
    throw new Error('OpenNext worker changed; review prewarm before applying');
  }
  if(normalized.includes(MARKER)){
    if(count(normalized,prewarm)!==1||normalized.includes(REQUEST_IMPORT))throw new Error('Incomplete OpenNext prewarm patch');
    return source;
  }
  if(count(normalized,REQUEST_IMPORT)!==1)throw new Error('OpenNext request import changed; review prewarm before applying');
  return normalized.replace(REQUEST_IMPORT,'').replace('export default {',prewarm).replaceAll('\n',newline);
}

function planPrewarm(root=path.resolve(__dirname,'..')){
  root=path.resolve(root);
  const sources=new Map();
  const read=file=>{
    const target=path.join(root,file),source=fs.readFileSync(target,'utf8');
    sources.set(target,source);return source;
  };
  for(const [name,version] of Object.entries(VERSIONS)){
    const installed=JSON.parse(read('node_modules/'+name+'/package.json')).version;
    if(installed!==version)throw new Error(`Unaudited prewarm dependency ${name}@${installed}; expected ${version}`);
  }
  const config=read('.open-next/server-functions/default/open-next.config.mjs');
  // Only the default caches are audited. The bundled server's preloader is patched below.
  if(!config.includes('var open_next_config_default = defineCloudflareConfig({});')||
    !config.includes('routePreloadingBehavior = "none"')){
    throw new Error('Prewarm supports only the audited default OpenNext configuration');
  }
  const server=read('.open-next/server-functions/default/handler.mjs');
  if(!server.endsWith('var handler2=await createMainHandler();export{handler2 as handler};\n')&&
    !server.endsWith('var handler2=await createMainHandler();export{handler2 as handler};\r\n')){
    throw new Error('OpenNext server export changed; review startup and environment capture');
  }
  const source=read('.open-next/worker.js');
  return {root,source,sources,worker:patchWorker(source),server:patchRoutes(server),entry:ENTRY,
    serverPath:path.join(root,'.open-next/server-functions/default/handler.mjs'),
    workerPath:path.join(root,'.open-next/worker.js'),entryPath:path.join(root,'.open-next/prewarm-worker.js')};
}

function applyPrewarm(plan){
  // A rebuilt server can change even when the generated worker template is identical.
  for(const [file,source] of plan.sources){
    if(fs.readFileSync(file,'utf8')!==source)throw new Error('OpenNext build changed; plan prewarm again');
  }
  fs.writeFileSync(plan.entryPath,plan.entry);
  fs.writeFileSync(plan.serverPath,plan.server);
  fs.writeFileSync(plan.workerPath,plan.worker);
  return plan.entryPath;
}

if(require.main===module){
  try{
    const mode=process.argv[2]||'--check';
    if(process.argv.length>3||!['--check','--apply'].includes(mode))throw new Error('Usage: node scripts/cloudflare-prewarm.cjs [--check|--apply]');
    const plan=planPrewarm();
    if(mode==='--apply')console.log('Generated prewarm entry:',applyPrewarm(plan));
    else console.log('Prewarm source checks passed; no files changed. Run tests/cloudflare-prewarm.test.cjs before --apply.');
  }catch(error){console.error(error.message);process.exitCode=1;}
}

module.exports={VERSIONS,MARKER,SERVER_IMPORT,ENTRY,ROUTE_CONFIG,WARM_ROUTE_CONFIG,PAGE_PRELOAD,STRICT_PAGE_PRELOAD,
  APP_PRELOAD,STRICT_APP_PRELOAD,patchRoutes,patchWorker,planPrewarm,applyPrewarm};
